### ISSUE TITLE
Spelling error in exception 'Staring time invalid'

### ISSUE THREAD

**Issue by brion** [captioning/captioning#43]
The SRT file parser throws an exception when a caption's starting time overlaps the previous caption, saying 'Staring time invalid'. Should be 'Starting time'.

Sample exception:

```
exception 'Exception' with message ' is not a proper .srt file. (00:00:25,700 --> 00:00:27,750: Staring time invalid: 00:00:25,700)' in /Users/brion/src/wiki/timedtext/vendor/captioning/captioning/src/Captioning/Format/SubripFile.php:110
Stack trace:
#0 /Users/brion/src/wiki/timedtext/vendor/captioning/captioning/src/Captioning/File.php(253): Captioning\Format\SubripFile->parse()
#1 /Users/brion/src/wiki/timedtext/convert-vtt.php(12): Captioning\File->loadFromString('\xEF\xBB\xBF1\n00:00:04,2...')
#2 /Users/brion/src/wiki/timedtext/convert-vtt.php(34): convert('srt/\xC2\xBFQue\xCC\x81_es_...', 'vtt/\xC2\xBFQue\xCC\x81_es_...')
#3 {main}
```

**Comment by delphiki** [comment]
Fixed, thanks!
